export default {
  "+ Add Horizontal Giude": "+Añadir guía horizontal",
  "+ Add Vertical Giude": "+ Añadir guía vertical",
  "2D View": "Vista 2D",
  "3D First Person": "Primera persona 3D",
  "3D View": "Vista 3D",
  "altitude": "altitud",
  "Altitude": "Altitud",
  "Areas": "Áreas",
  "Cancel": "Cancelar",
  "Catalog": "Catálogo",
  "Chain selected Elements to Group": "Chain selected Elements to Group",
  "Circular": "Circular",
  "color": "color",
  "Configure layer": "Configuración plantilla",
  "Configure project": "Configurar proyecto",
  "Confirm": "Confirmar",
  "Copy": "Copiar",
  "Delete group and all Elements": "Borrar grupo y todos los elementos",
  "Delete layer": "Borrar plantilla",
  "Delete": "Borrar",
  "Elements on layer {0}": "Elementos en plantilla {0}",
  "Elements": "Elementos",
  "Get Screenshot": "Tomar captura de pantalla",
  "Group [{0}]": "Group [{0}]",
  "Group's Barycenter": "Group's Barycenter",
  "Group's Elements": "Group's Elements",
  "Groups": "Grupos",
  "Guides": "Guías",
  "height": "Altura",
  "Holes": "Holes",
  "Horizontal": "Horizontal",
  "Items": "Objetos",
  "Last Selected": "Último elejido",
  "Layer config": "Configuracion de plantilla",
  "Layer": "Plantilla",
  "Layers": "Plantillas",
  "Length": "Longitud",
  "Lines": "Lineas",
  "Load project": "Cargar proyecto",
  "Mouse X Coordinate": "Coordenadas X mouse",
  "Mouse Y Coordinate": "Coordenadas Y mouse",
  "Name": "Nombre",
  "New Empty Group": "Nuevo grupo vacío",
  "New Group from selected": "Nuevo grupo de selección",
  "New layer": "Nueva plantilla",
  "New project": "Nuevo proyecto",
  "opacity": "Opacidad",
  "Open catalog": "Abrir Catalogo",
  "order": "ordenar",
  "Pan": "Pan",
  "Paste": "Pegar",
  "Project config": "Configurar Proyecto",
  "Properties: [{0}] {1}": "Propiedades: [{0}] {1}",
  "Prototype": "Prototype",
  "Reset": "Reiniciar",
  "Rotation": "Rotar",
  "Save project": "Guardar Proyecto",
  "Save": "Guardar",
  "Scene Zoom Level": "Escena nivel de zoom",
  "Search Element": "Buscar elemento",
  "Snap to Grid": "Snap to Grid",
  "Snap to Guide": "Snap to Guide",
  "Snap to Line": "Snap to Line",
  "Snap to Point": "Snap to Point",
  "Snap to Segment": "Snap to Segment",
  "texture": "textura",
  "thickness": "thickness",
  "Toggle Group Visibility": "Mostrar/ocultar grupo de visibilidad",
  "Un-chain all Group\'s Elements and remove Group": "Un-chain all Group\'s Elements and remove Group",
  "Un-chain Element from Group": "Un-chain Element from Group",
  "Undo (CTRL-Z)": "Regresar cambio (CTRL-Z)",
  "Unselect": "Desmarcar",
  "Vertical": "Vertical",
  "width": "ancho",
  "Would you want to start a new Project?": "Te gustaría inicar un nuevo pryecto?",
  "Zoom in": "+Zoom",
  "Zoom out": "-Zoom"
};
